export const plugins = {
  setup: [
    {
      name: "Databases",
      notes: "",
      route: "db",
      enabled: true,
      pluginPath: "plugins/Setup/Db/module",
      description: "Database connection and credentials",
    },
    {
      name: "Azure AD integration",
      notes:
        "Notes: Require manual update of the environment variable to switch the identity provider to Azure",
      route: "azure-ad",
      enabled: false,
      pluginPath: "plugins/Setup/AzureAD/module",
      description: "Allow user to sign-in with Azure Active Directory",
    },
    {
      name: "Feature flags",
      route: "feature",
      enabled: true,
      pluginPath: "plugins/Setup/Feature/module",
      description: "Enable / disable feature",
    },
    {
      name: "Metadata",
      notes: "",
      route: "metadata",
      enabled: true,
      pluginPath: "plugins/Setup/Metadata/module",
      description: "Configure dataset metadata and tags",
    },
    {
      name: "Patient Analytics Config",
      notes: "",
      route: "pa-config",
      enabled: true,
      pluginPath: "plugins/mri/PatientAnalyticsConfig/module",
      description: "Configure patient analytics",
    },
    {
      name: "CDM Config",
      notes: "",
      route: "cdm-config",
      enabled: true,
      pluginPath: "plugins/mri/CDM/module",
      description: "Configure CDM",
    },
    {
      name: "Patient Summary Config",
      notes: "",
      route: "ps-config",
      enabled: false,
      pluginPath: "plugins/mri/PatientSummaryConfig/module",
      description: "Configure patient summary",
    },
    {
      name: "Overview description",
      notes: "",
      route: "overview-description",
      enabled: true,
      pluginPath: "plugins/Setup/OverviewDescription/module",
      description: "Configure overview description text",
    },
    {
      name: "Hybrid Search",
      notes: "",
      route: "hybrid-search",
      enabled: true,
      pluginPath: "plugins/Setup/HybridSearch/module",
      description: "Configure hybrid search for concepts",
    },
    {
      name: "Plugins",
      notes: "",
      route: "plugins",
      enabled: true,
      pluginPath: "plugins/Setup/TrexPlugins/module",
      description: "Manage plugins",
    },
    {
      name: "Demo setup",
      notes: "",
      route: "demo-setup",
      enabled: true,
      pluginPath: "plugins/Setup/DemoSetup/module",
      description: "Setting up demo dataset",
    },
  ],
  researcher: [
    {
      name: "Concepts",
      route: "concepts",
      enabled: true,
      pluginPath: "plugins/Researcher/ConceptSets/module",
      featureFlag: "conceptSets",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Cohorts",
      route: "cohort",
      enabled: true,
      pluginPath: "plugins/mri/PatientAnalytics/module",
      featureFlag: "cohort",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Cohorts M",
      route: "cohorts",
      enabled: false,
      pluginPath: "plugins/Cohort/module",
      featureFlag: "cohorts",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Notebooks",
      route: "starboard",
      enabled: true,
      subMenus: "true",
      pluginPath: "plugins/Starboard/module",
      featureFlag: "starboard",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Analysis",
      route: "analysis_parent",
      enabled: true,
      children: [
        {
          name: "Strategus",
          route: "analysis",
          enabled: false,
          pluginPath: "https://localhost:41100/analysis/module.js",
          featureFlag: "strategus",
          requiredRoles: ["RESEARCHER"],
        },
      ],
      requiredRoles: ["RESEARCHER"],
    },
  ],
  systemadmin: [
    {
      name: "Users",
      route: "user-overview",
      enabled: true,
      pluginPath: "plugins/SystemAdmin/UserOverview/module",
    },
    {
      name: "Datasets",
      route: "dataset-overview",
      enabled: true,
      pluginPath: "plugins/SystemAdmin/StudyOverview/module",
    },
    {
      name: "Jobs",
      route: "jobs",
      enabled: true,
      pluginPath: "plugins/SystemAdmin/Jobs/module",
    },
    {
      name: "ETL",
      route: "etl",
      enabled: true,
      children: [
        {
          name: "Concept mapping",
          route: "concept-mapping",
          enabled: true,
          pluginPath: "plugins/SystemAdmin/ConceptMapping/module",
        },
        {
          data: { mappingSuggestion: false },
          name: "Data mapping",
          route: "data-mapping",
          enabled: true,
          pluginPath: "https://localhost:41100/mapping/module.js",
        },
        {
          data: { dnBaseUrl: "https://localhost:41100/" },
          name: "Data transformation",
          route: "dataflow",
          enabled: true,
          pluginPath: "https://localhost:41100/flow/module.js",
        },
      ],
    },
    {
      name: "Setup",
      route: "setup",
      enabled: true,
      pluginPath: "plugins/Setup/module",
    },
  ],
};

export const uiPlugins = {
  researcher: [
    {
      route: "analysis_parent",
      children: [
        {
          enabled: true,
          featureFlag: "cohortSurvival",
          name: "Cohort Survival",
          pluginPath: "plugins/Researcher/CohortSurvival/module",
          requiredRoles: ["RESEARCHER"],
          route: "cohort-survival",
        },
      ],
    },
  ],
};
export const expected = {
  setup: [
    {
      name: "Databases",
      notes: "",
      route: "db",
      enabled: true,
      pluginPath: "plugins/Setup/Db/module",
      description: "Database connection and credentials",
    },
    {
      name: "Azure AD integration",
      notes:
        "Notes: Require manual update of the environment variable to switch the identity provider to Azure",
      route: "azure-ad",
      enabled: false,
      pluginPath: "plugins/Setup/AzureAD/module",
      description: "Allow user to sign-in with Azure Active Directory",
    },
    {
      name: "Feature flags",
      route: "feature",
      enabled: true,
      pluginPath: "plugins/Setup/Feature/module",
      description: "Enable / disable feature",
    },
    {
      name: "Metadata",
      notes: "",
      route: "metadata",
      enabled: true,
      pluginPath: "plugins/Setup/Metadata/module",
      description: "Configure dataset metadata and tags",
    },
    {
      name: "Patient Analytics Config",
      notes: "",
      route: "pa-config",
      enabled: true,
      pluginPath: "plugins/mri/PatientAnalyticsConfig/module",
      description: "Configure patient analytics",
    },
    {
      name: "CDM Config",
      notes: "",
      route: "cdm-config",
      enabled: true,
      pluginPath: "plugins/mri/CDM/module",
      description: "Configure CDM",
    },
    {
      name: "Patient Summary Config",
      notes: "",
      route: "ps-config",
      enabled: false,
      pluginPath: "plugins/mri/PatientSummaryConfig/module",
      description: "Configure patient summary",
    },
    {
      name: "Overview description",
      notes: "",
      route: "overview-description",
      enabled: true,
      pluginPath: "plugins/Setup/OverviewDescription/module",
      description: "Configure overview description text",
    },
    {
      name: "Hybrid Search",
      notes: "",
      route: "hybrid-search",
      enabled: true,
      pluginPath: "plugins/Setup/HybridSearch/module",
      description: "Configure hybrid search for concepts",
    },
    {
      name: "Plugins",
      notes: "",
      route: "plugins",
      enabled: true,
      pluginPath: "plugins/Setup/TrexPlugins/module",
      description: "Manage plugins",
    },
    {
      name: "Demo setup",
      notes: "",
      route: "demo-setup",
      enabled: true,
      pluginPath: "plugins/Setup/DemoSetup/module",
      description: "Setting up demo dataset",
    },
  ],
  researcher: [
    {
      name: "Concepts",
      route: "concepts",
      enabled: true,
      pluginPath: "plugins/Researcher/ConceptSets/module",
      featureFlag: "conceptSets",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Cohorts",
      route: "cohort",
      enabled: true,
      pluginPath: "plugins/mri/PatientAnalytics/module",
      featureFlag: "cohort",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Cohorts M",
      route: "cohorts",
      enabled: false,
      pluginPath: "plugins/Cohort/module",
      featureFlag: "cohorts",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Notebooks",
      route: "starboard",
      enabled: true,
      subMenus: "true",
      pluginPath: "plugins/Starboard/module",
      featureFlag: "starboard",
      requiredRoles: ["RESEARCHER"],
    },
    {
      name: "Analysis",
      route: "analysis_parent",
      enabled: true,
      children: [
        {
          name: "Strategus",
          route: "analysis",
          enabled: false,
          pluginPath: "https://localhost:41100/analysis/module.js",
          featureFlag: "strategus",
          requiredRoles: ["RESEARCHER"],
        },
        {
          enabled: true,
          featureFlag: "cohortSurvival",
          name: "Cohort Survival",
          pluginPath: "plugins/Researcher/CohortSurvival/module",
          requiredRoles: ["RESEARCHER"],
          route: "cohort-survival",
        },
      ],
      requiredRoles: ["RESEARCHER"],
    },
  ],
  systemadmin: [
    {
      name: "Users",
      route: "user-overview",
      enabled: true,
      pluginPath: "plugins/SystemAdmin/UserOverview/module",
    },
    {
      name: "Datasets",
      route: "dataset-overview",
      enabled: true,
      pluginPath: "plugins/SystemAdmin/StudyOverview/module",
    },
    {
      name: "Jobs",
      route: "jobs",
      enabled: true,
      pluginPath: "plugins/SystemAdmin/Jobs/module",
    },
    {
      name: "ETL",
      route: "etl",
      enabled: true,
      children: [
        {
          name: "Concept mapping",
          route: "concept-mapping",
          enabled: true,
          pluginPath: "plugins/SystemAdmin/ConceptMapping/module",
        },
        {
          data: { mappingSuggestion: false },
          name: "Data mapping",
          route: "data-mapping",
          enabled: true,
          pluginPath: "https://localhost:41100/mapping/module.js",
        },
        {
          data: { dnBaseUrl: "https://localhost:41100/" },
          name: "Data transformation",
          route: "dataflow",
          enabled: true,
          pluginPath: "https://localhost:41100/flow/module.js",
        },
      ],
    },
    {
      name: "Setup",
      route: "setup",
      enabled: true,
      pluginPath: "plugins/Setup/module",
    },
  ],
};
