import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://localhost:443');
  await page.getByTestId('button').nth(1).click();
  await page.locator('input[name="identifier"]').click();
  await page.locator('input[name="identifier"]').fill('admin');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('Updatepassword12345');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByTestId('button').nth(1).click();
  await page.getByRole('button', { name: 'Dataset' }).click();
  await page.getByRole('option', { name: 'synpuf5pct' }).click();
  await page.getByRole('link', { name: 'Cohorts' }).click();
  await page.getByRole('button', { name: 'D2E' }).click();
  await page.getByTitle('Basic Data - Age').click();
  await page.getByRole('textbox').fill('[20-30]');
  await page.getByText('All').click();
  await page.getByRole('textbox', { name: 'Enter search term' }).fill('Male');
  await page.getByText('MALE - MALE').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Enter name' }).click();
  await page.getByRole('textbox', { name: 'Enter name' }).fill('Cohort_Test_1');
  await page.getByTitle('Allow bookmark to be visible').locator('div').click();
  await page.locator('footer').getByRole('button', { name: 'Save' }).click();
  await page.locator('#pane-left').getByRole('link', { name: 'Cohorts' }).click();
  await page.getByRole('button', { name: 'D2E' }).click();
  await page.getByTitle('Basic Data - Age').click();
  await page.getByRole('textbox').fill('[30-40]');
  await page.getByText('All').click();
  await page.getByRole('textbox', { name: 'Enter search term' }).fill('Female');
  await page.getByText('FEMALE - FEMALE').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Enter name' }).fill('Cohort_test_2');
  await page.getByTitle('Allow bookmark to be visible').locator('div').click();
  await page.locator('footer').getByRole('button', { name: 'Save' }).click();
  await page.locator('#pane-left').getByRole('link', { name: 'Cohorts' }).click();
  await page.getByRole('button', { name: '' }).click();
  await page.locator('[id="0.-Icons/Play_Round-Copy-12"] > #Combined-Shape').first().click();
  await page.locator('div:nth-child(2) > .footer > div > svg').first().click();
  await page.getByRole('button', { name: 'Compare' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Account' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByTestId('button').nth(1).click();
  await page.locator('input[name="identifier"]').click();
  await page.locator('input[name="identifier"]').fill('admin');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('Updatepassword12345');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByTestId('button').nth(1).click();
  await page.getByRole('link', { name: 'Cohorts' }).click();
  await page.locator('#pane-left label div').click();
  await page.locator('div:nth-child(2) > .footer > div > svg').first().click();
  await page.locator('.icon-button > svg').first().click();
  await page.locator('[id="0.-Icons/Play_Round-Copy-13"] > #Group > #Path').first().click();
  await page.locator('div:nth-child(2) > .footer > div:nth-child(3) > svg').click();
  await page.getByRole('textbox', { name: 'Enter description' }).click();
  await page.getByRole('textbox', { name: 'Enter description' }).fill('test_description');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('div:nth-child(2) > .footer > div:nth-child(2) > svg').click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('Cohort_Test_10');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('div:nth-child(4) > svg').first().click();
  await page.locator('div:nth-child(5) > svg > path').first().click();
  await page.locator('div:nth-child(5) > svg').first().click();
  await page.getByRole('button', { name: 'Delete' }).click();
});
