import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
  await page.goto('https://localhost:443')
  await page.getByTestId('button').nth(1).click()
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByTestId('button').nth(1).click()
  await page.getByRole('button', { name: 'Switch to Admin portal' }).click()
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^MetadataConfigure dataset metadata and tagsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByRole('textbox', { name: 'Attribute Id' }).click()
  await page.getByRole('textbox', { name: 'Attribute Id' }).fill('test_input')
  await page.getByRole('textbox', { name: 'Attribute Name' }).click()
  await page.getByRole('textbox', { name: 'Attribute Name' }).fill('Test input')
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('link', { name: 'Datasets' }).click()
  await page.getByRole('row', { name: 'Normal 67f4015c-04f0-4a92-' }).getByRole('button').nth(2).click()
  await page.getByRole('option', { name: 'Update dataset' }).click()
  await page.getByRole('button', { name: 'add metadata' }).click()
  await page
    .locator(
      'div:nth-child(11) > .u-padding-vertical--small > .MuiFormControl-root > .MuiInput-root > .MuiSelect-select'
    )
    .click()
  await page.getByRole('option', { name: 'Test input' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^Test inputValue$/ })
    .getByPlaceholder(' ')
    .click()
  await page
    .locator('div')
    .filter({ hasText: /^Test inputValue$/ })
    .getByPlaceholder(' ')
    .fill('text input')
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^MetadataConfigure dataset metadata and tagsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByRole('row', { name: 'test_input Test input DATASET' }).getByRole('button').first().click()
  await page.getByRole('button', { name: 'Datatype STRING' }).click()
  await page.getByRole('option', { name: 'NUMBER' }).click()
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('link', { name: 'Datasets' }).click()
  await page.getByRole('row', { name: 'Normal 67f4015c-04f0-4a92-' }).getByRole('button').nth(2).click()
  await page.getByRole('option', { name: 'Update dataset' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^Test inputValue$/ })
    .getByPlaceholder(' ')
    .click()
  await page
    .locator('div')
    .filter({ hasText: /^Test inputValue$/ })
    .getByPlaceholder(' ')
    .fill('123')
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^MetadataConfigure dataset metadata and tagsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByRole('row', { name: 'test_input Test input DATASET' }).getByRole('button').first().click()
  await page.getByRole('button', { name: 'Datatype NUMBER' }).click()
  await page.getByRole('option', { name: 'TIMESTAMP' }).click()
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('link', { name: 'Datasets' }).click()
  await page.getByRole('row', { name: 'Normal 67f4015c-04f0-4a92-' }).getByRole('button').nth(2).click()
  await page.getByRole('option', { name: 'Update dataset' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^Test inputValue$/ })
    .getByPlaceholder(' ')
    .fill('2025-08-07')
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^MetadataConfigure dataset metadata and tagsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByRole('row', { name: 'test_input Test input DATASET' }).getByRole('button').nth(1).click()
  await page.getByRole('button', { name: 'Delete' }).click()
})
