automation:
  enabled: false
  rules:
    - patterns:
        - "*"
      profile: default

profiles:
  default:
    duration: 1h
    pass_threshold: 60
    allowed_voters:
      teams: []
      users:
        - csafreen
        - p-hoffmann
        - SantanM
        - satish-a0
        - suwarnoong 
    periodic_status_check: null
    close_on_passing: true
    close_on_passing_min_wait: null
    
