export const attributeMap = {
  ConditionEra: {
    startDate: 'EraStartDate',
    endDate: 'EraEndDate',
    occurrenceCount: 'OccurrenceCount',
    eraLength: 'EraLength',
    first: 'First',
    ageAtStart: 'AgeAtStart',
    ageAtEnd: 'AgeAtEnd',
    dateAdjustment: 'DateAdjustment',
  },
  ConditionOccurrence: {
    startDate: 'OccurrenceStartDate',
    endDate: 'OccurrenceEndDate',
    occurrenceCount: 'OccurrenceCount',
    exclude: 'ConditionTypeExclude',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
    stopReason: 'StopReason',
  },
  Death: {
    startDate: 'OccurrenceStartDate',
    endDate: 'OccurrenceEndDate',
    exclude: 'DeathTypeExclude',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  DemographicCriteria: {
    startDate: 'OccurrenceStartDate',
    endDate: 'OccurrenceEndDate',
    age: 'Age',
    gender: 'Gender',
    race: 'Race',
    ethnicity: 'Ethnicity',
  },
  DeviceExposure: {
    startDate: 'OccurrenceStartDate',
    endDate: 'OccurrenceEndDate',
    exclude: 'DeviceTypeExclude',
    deviceId: 'UniqueDeviceId',
    quantity: 'Quantity',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  DoseEra: {
    startDate: 'EraStartDate',
    endDate: 'EraEndDate',
    doseValue: 'DoseValue',
    eraLength: 'EraLength',
    first: 'First',
    ageAtStart: 'AgeAtStart',
    ageAtEnd: 'AgeAtEnd',
    dateAdjustment: 'DateAdjustment',
  },
  DrugEra: {
    startDate: 'EraStartDate',
    endDate: 'EraEndDate',
    occurrenceCount: 'OccurrenceCount',
    gapDays: 'GapDays',
    eraLength: 'EraLength',
    first: 'First',
    ageAtStart: 'AgeAtStart',
    ageAtEnd: 'AgeAtEnd',
    dateAdjustment: 'DateAdjustment',
  },
  DrugExposure: {
    startDate: 'OccurrenceStartDate',
    endDate: 'OccurrenceEndDate',
    exclude: 'DrugTypeExclude',
    stopReason: 'StopReason',
    refills: 'Refills',
    quantity: 'Quantity',
    daysSupply: 'DaysSupply',
    effectiveDrugDose: 'EffectiveDrugDose',
    lotNumber: 'LotNumber',
    routeConcept: 'RouteConcept',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  LocationRegion: {
    startDate: 'StartDate',
    endDate: 'EndDate',
  },
  Measurement: {
    first: 'First',
    startDate: 'OccurrenceStartDate',
    exclude: 'MeasurementTypeExclude',
    valueAsNumber: 'ValueAsNumber',
    rangeLow: 'RangeLow',
    rangeHigh: 'RangeHigh',
    rangeLowRatio: 'RangeLowRatio',
    rangeHighRatio: 'RangeHighRatio',
    abnormal: 'Abnormal',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  Observation: {
    startDate: 'OccurrenceStartDate',
    exclude: 'ObservationTypeExclude',
    valueAsNumber: 'ValueAsNumber',
    valueAsString: 'ValueAsString',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  ObservationPeriod: {
    first: 'First',
    startDate: 'PeriodStartDate',
    endDate: 'PeriodEndDate',
    userDefinedPeriod: 'UserDefinedPeriod',
    ageAtStart: 'AgeAtStart',
    ageAtEnd: 'AgeAtEnd',
    periodLength: 'PeriodLength',
    dateAdjustment: 'DateAdjustment',
  },
  PayerPlanPeriod: {
    first: 'First',
    startDate: 'PeriodStartDate',
    endDate: 'PeriodEndDate',
    userDefinedPeriod: 'UserDefinedPeriod',
    periodLength: 'PeriodLength',
    ageAtStart: 'AgeAtStart',
    ageAtEnd: 'AgeAtEnd',
    dateAdjustment: 'DateAdjustment',
  },
  ProcedureOccurrence: {
    startDate: 'OccurrenceStartDate',
    exclude: 'ProcedureTypeExclude',
    quantity: 'Quantity',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  Specimen: {
    startDate: 'OccurrenceStartDate',
    exclude: 'SpecimenTypeExclude',
    quantity: 'Quantity',
    sourceId: 'SourceId',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  VisitDetail: {
    startDate: 'VisitDetailStartDate',
    endDate: 'VisitDetailEndDate',
    visitDetailLength: 'VisitDetailLength',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
  VisitOccurrence: {
    startDate: 'OccurrenceStartDate',
    endDate: 'OccurrenceEndDate',
    exclude: 'VisitTypeExclude',
    visitLength: 'VisitLength',
    first: 'First',
    age: 'Age',
    dateAdjustment: 'DateAdjustment',
  },
}

export const atlasToCriteriaAttrMap = {
  EraStartDate: 'startDate',
  EraEndDate: 'endDate',
  OccurrenceCount: 'occurrenceCount',
  EraLength: 'eraLength',
  First: 'first',
  AgeAtStart: 'ageAtStart',
  AgeAtEnd: 'ageAtEnd',
  DateAdjustment: 'dateAdjustment',
  OccurrenceStartDate: 'startDate',
  OccurrenceEndDate: 'endDate',
  ConditionTypeExclude: 'exclude',
  Age: 'age',
  DeathTypeExclude: 'exclude',
  DeviceTypeExclude: 'exclude',
  UniqueDeviceId: 'deviceId',
  Quantity: 'quantity',
  DoseValue: 'doseValue',
  GapDays: 'gapDays',
  DrugTypeExclude: 'exclude',
  StopReason: 'stopReason',
  Refills: 'refills',
  DaysSupply: 'daysSupply',
  EffectiveDrugDose: 'effectiveDrugDose',
  LotNumber: 'lotNumber',
  RouteConcept: 'routeConcept',
  StartDate: 'startDate',
  EndDate: 'endDate',
  MeasurementTypeExclude: 'exclude',
  ValueAsNumber: 'valueAsNumber',
  RangeLow: 'rangeLow',
  RangeHigh: 'rangeHigh',
  RangeLowRatio: 'rangeLowRatio',
  RangeHighRatio: 'rangeHighRatio',
  Abnormal: 'abnormal',
  ObservationTypeExclude: 'exclude',
  ValueAsString: 'valueAsString',
  PeriodStartDate: 'startDate',
  PeriodEndDate: 'endDate',
  UserDefinedPeriod: 'userDefinedPeriod',
  PeriodLength: 'periodLength',
  ProcedureTypeExclude: 'exclude',
  SpecimenTypeExclude: 'exclude',
  SourceId: 'sourceId',
  VisitDetailStartDate: 'startDate',
  VisitDetailEndDate: 'endDate',
  VisitDetailLength: 'visitDetailLength',
  VisitTypeExclude: 'exclude',
  VisitLength: 'visitLength',
}
