const _env = Deno.env.toObject();

export const env = {
  FHIR_SERVER_BASE_URL: _env.FHIR_SERVER_BASE_URL,
  PG__HOST: _env.PG__HOST,
  PG__PORT: _env.PG__PORT,
  PG__DB_NAME: _env.PG__DB_NAME,
  PG_SUPER_USER: _env.PG_SUPER_USER,
  PG_SUPER_PASSWORD: _env.PG_SUPER_PASSWORD,
  REDIS_HOST: _env.REDIS_HOST,
  REDIS_PORT: _env.REDIS_PORT,
  REDIS_PASSWORD: _env.REDIS_PASSWORD,
  FHIR__CLIENT_ID: _env.FHIR__CLIENT_ID,
  FHIR__CLIENT_SECRET: _env.FHIR__CLIENT_SECRET,
  FHIR__LOG_LEVEL: _env.FHIR__LOG_LEVEL,
  SERVICE_ROUTES: _env.SERVICE_ROUTES || '{}',
  BINARY_UPLOAD_LIMIT_SIZE: _env.BINARY_UPLOAD_LIMIT_SIZE,
  FHIR_CUSTOM_SCHEMA: _env.FHIR_CUSTOM_SCHEMA,
  MEDPLUM_PLUGIN_PATH: _env.MEDPLUM_PLUGIN_PATH,
  FHIR_FUNCTIONS_PLUGIN_PATH: _env.FHIR_FUNCTIONS_PLUGIN_PATH,
}

export const services = JSON.parse(env.SERVICE_ROUTES)
export const binaryUploadLimitSize = env.BINARY_UPLOAD_LIMIT_SIZE