--liquibase formatted sql
--changeset alp:V1.0.0.0.1__create_waveform_indices


CREATE INDEX IDX_WAVEFORM_OCC_PERSON_ID ON WAVEFORM_OCCURRENCE (PERSON_ID ASC);
CREATE INDEX IDX_WAVEFORM_OCC_VISIT_ID ON WAVEFORM_OCCURRENCE (VISIT_OCCURRENCE_ID ASC);
CREATE INDEX IDX_WAVEFORM_OCC_CONCEPT_ID ON WAVEFORM_OCCURRENCE (WAVEFORM_OCCURRENCE_CONCEPT_ID ASC);

CREATE INDEX IDX_WAVEFORM_REG_OCC_ID ON WAVEFORM_REGISTRY (WAVEFORM_OCCURRENCE_ID ASC);
CREATE INDEX IDX_WAVEFORM_REG_PERSON_ID ON WAVEFORM_REGISTRY (PERSON_ID ASC);

CREATE INDEX IDX_WAVEFORM_CHNL_REG_ID ON WAVEFORM_CHANNEL_METADATA (WAVEFORM_REGISTRY_ID ASC);
CREATE INDEX IDX_WAVEFORM_CHNL_CONCEPT_ID ON WAVEFORM_CHANNEL_METADATA (CHANNEL_CONCEPT_ID ASC);

CREATE INDEX IDX_WAVEFORM_FEAT_OCC_ID ON WAVEFORM_FEATURE (WAVEFORM_OCCURRENCE_ID ASC);
CREATE INDEX IDX_WAVEFORM_FEAT_REG_ID ON WAVEFORM_FEATURE (WAVEFORM_REGISTRY_ID ASC);
CREATE INDEX IDX_WAVEFORM_FEAT_CHNL_ID ON WAVEFORM_FEATURE (WAVEFORM_CHANNEL_METADATA_ID ASC);


--rollback DROP INDEX IDX_WAVEFORM_OCC_PERSON_ID;
--rollback DROP INDEX IDX_WAVEFORM_OCC_VISIT_ID;
--rollback DROP INDEX IDX_WAVEFORM_OCC_CONCEPT_ID;
--rollback DROP INDEX IDX_WAVEFORM_REG_OCC_ID;
--rollback DROP INDEX IDX_WAVEFORM_REG_PERSON_ID;
--rollback DROP INDEX IDX_WAVEFORM_CHNL_REG_ID;
--rollback DROP INDEX IDX_WAVEFORM_CHNL_CONCEPT_ID;
--rollback DROP INDEX IDX_WAVEFORM_FEAT_OCC_ID;
--rollback DROP INDEX IDX_WAVEFORM_FEAT_REG_ID;
--rollback DROP INDEX IDX_WAVEFORM_FEAT_CHNL_ID;
