--liquibase formatted sql
--changeset alp:V1.0.0.0.0__create_waveform_tables


CREATE TABLE WAVEFORM_OCCURRENCE(
  WAVEFORM_OCCURRENCE_ID INTEGER NOT NULL,
  WAVEFORM_OCCURRENCE_CONCEPT_ID INTEGER NOT NULL,
  PERSON_ID INTEGER NOT NULL,
  WAVEFORM_OCCURRENCE_START_DATETIME TIMESTAMP NOT NULL,
  WAVEFORM_OCCURRENCE_END_DATETIME TIMESTAMP NOT NULL,
  VISIT_OCCURRENCE_ID INTEGER NOT NULL,
  VISIT_DETAIL_ID INTEGER,
  PRECEDING_WAVEFORM_OCCURRENCE_ID INTEGER,
  WAVEFORM_FORMAT_CONCEPT_ID INTEGER,
  WAVEFORM_OCCURRENCE_SOURCE_VALUE NVARCHAR(255),
  NUM_OF_FILES INTEGER,
  WAVEFORM_FORMAT_SOURCE_VALUE NVARCHAR(50)
);


CREATE TABLE WAVEFORM_REGISTRY(
  WAVEFORM_REGISTRY_ID INTEGER NOT NULL,
  WAVEFORM_OCCURRENCE_ID INTEGER NOT NULL,
  WAVEFORM_FEATURE_ID INTEGER,
  PERSON_ID INTEGER NOT NULL,
  WAVEFORM_FILE_START_DATETIME TIMESTAMP NOT NULL,
  WAVEFORM_FILE_END_DATETIME TIMESTAMP NOT NULL,
  VISIT_OCCURRENCE_ID INTEGER NOT NULL,
  VISIT_DETAIL_ID INTEGER,
  FILE_EXTENSION_CONCEPT_ID INTEGER,
  FILE_EXTENSION_SOURCE_VALUE NVARCHAR(50) NOT NULL,
  WAVEFORM_SOURCE_FILE_URI NVARCHAR(10000),
  WAVEFORM_TARGET_FILE_URI NVARCHAR(10000) NOT NULL
);


CREATE TABLE WAVEFORM_CHANNEL_METADATA(
  WAVEFORM_CHANNEL_METADATA_ID INTEGER NOT NULL,
  WAVEFORM_REGISTRY_ID INTEGER NOT NULL,
  PROCEDURE_OCCURRENCE_ID INTEGER,
  DEVICE_EXPOSURE_ID INTEGER,
  WAVEFORM_CHANNEL_SOURCE_VALUE NVARCHAR(50),
  CHANNEL_CONCEPT_ID INTEGER NOT NULL,
  METADATA_SOURCE_VALUE NVARCHAR(50) NOT NULL,
  METADATA_CONCEPT_ID INTEGER NOT NULL,
  VALUE_AS_NUMBER NUMERIC,
  VALUE_AS_CONCEPT_ID INTEGER,
  VALUE_AS_STRING NVARCHAR(255),
  UNIT_CONCEPT_ID INTEGER,
  UNIT_SOURCE_VALUE NVARCHAR(50)
);


CREATE TABLE WAVEFORM_FEATURE(
  WAVEFORM_FEATURE_ID INTEGER NOT NULL,
  WAVEFORM_OCCURRENCE_ID INTEGER NOT NULL,
  WAVEFORM_REGISTRY_ID INTEGER NOT NULL,
  WAVEFORM_CHANNEL_METADATA_ID INTEGER NOT NULL,
  MEASUREMENT_ID INTEGER,
  OBSERVATION_ID INTEGER,
  ALGORITHM_CONCEPT_ID INTEGER NOT NULL,
  ALGORITHM_SOURCE_VALUE NVARCHAR(255),
  ANATOMIC_SITE_CONCEPT_ID INTEGER,
  WAVEFORM_FEATURE_START_TIMESTAMP TIME,
  WAVEFORM_FEATURE_END_TIMESTAMP TIME,
  IS_FEATURE_OVERFLOW BOOLEAN,
  VALUE_AS_NUMBER NUMERIC,
  VALUE_AS_CONCEPT_ID INTEGER,
  VALUE_AS_STRING NVARCHAR(255),
  VALUE_IS_A_REGISTRY_FILE BOOLEAN,
  UNIT_CONCEPT_ID INTEGER,
  UNIT_SOURCE_VALUE NVARCHAR(50)
);


--rollback DROP TABLE WAVEFORM_OCCURRENCE;
--rollback DROP TABLE WAVEFORM_REGISTRY;
--rollback DROP TABLE WAVEFORM_CHANNEL_METADATA;
--rollback DROP TABLE WAVEFORM_FEATURE;
