import { test, expect } from '@playwright/test'

test('Concepts', async ({ page }) => {
  await page.goto('https://localhost:443/portal')
  await page.locator('input[name="identifier"]').dblclick()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByText('Demo dataset').first().click()
  await page.getByRole('link', { name: 'Concepts' }).click()
  await expect(page.getByText('1–25 of 444')).toBeVisible()
  await expect(page).toHaveScreenshot({ maxDiffPixels: 100 })
  await page.getByRole('tab', { name: 'Concept Sets' }).click()
  await page.getByTestId('button').click() // click on the "Add concept set" button
  await page.getByRole('textbox', { name: 'search terms' }).click()
  await page.getByRole('textbox', { name: 'search terms' }).fill('Type 2 diabetes mellitus')
  await page.getByRole('button', { name: 'Search' }).click()
  await page.getByRole('row', { name: '4144583 427089005 Diabetes' }).locator('path').click()
  await page.getByRole('tab', { name: 'Selected concepts' }).click()
  await expect(page.getByRole('checkbox').nth(1)).toBeVisible()
  await page.getByRole('tab', { name: 'Related concepts' }).click()
  await page.getByRole('textbox', { name: 'Concept set name' }).click()
  await page.getByRole('textbox', { name: 'Concept set name' }).fill('Concept Set Test1')
  await page.getByRole('button', { name: 'Create' }).click()
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('link', { name: 'Cohorts' }).click()
  await page.getByRole('button', { name: 'D2E' }).click()
  await page.getByTitle('Add Filter Card').getByRole('button').click()
  await page.getByRole('menuitem', { name: 'Condition Occurrence' }).click()
  await page.locator('[id="__BVID__157__BV_toggle_"]').click()
  await page.getByRole('menu', { name: '' }).press('Escape')
  await page.locator('[id="patient\\.interactions\\.conditionoccurrence\\.1"]').getByText('All').click()
  await page.getByRole('textbox', { name: 'Enter search term' }).click()
  await page.getByRole('textbox', { name: 'Enter search term' }).fill('Concept Set Test1')
  await page.getByRole('textbox', { name: 'Enter search term' }).press('Enter')
  await page.getByText('Concept Set Test1').click()
  await page.getByText('✎').click()
  await page.getByRole('textbox', { name: 'search terms' }).click()
  await page.getByRole('textbox', { name: 'search terms' }).fill('Ulcerative colitis')
  await page.getByRole('textbox', { name: 'search terms' }).press('Enter')
  await page.getByRole('row', { name: '81893 64766004 Ulcerative' }).locator('path').click()
  await page.getByRole('button', { name: 'Update' }).click()
  await page.getByRole('button', { name: 'Close' }).click()
  await expect(page.locator('.swdrag')).toBeVisible()
  await expect(page).toHaveScreenshot({ maxDiffPixels: 100 })
})
