import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
  test.setTimeout(300 * 1000) // Set timeout to 5 minutes
  await page.goto('https://localhost:443/portal')
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')

  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByTestId('button').nth(1).click()
  await page.getByRole('button', { name: 'Switch to Admin portal' }).click()
  await page.getByRole('link', { name: 'Setup' }).click()

  // Create a new CDM configuration
  await page
    .locator('div')
    .filter({ hasText: /^CDM configurationConfigure CDMConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByRole('button', { name: 'Create Configuration' }).click()
  await page.getByRole('textbox', { name: 'Title Enter name for' }).fill('TestConfig101')
  await page.waitForTimeout(1000)
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.waitForTimeout(1000)
  await expect(page.locator('[id*="--pageMxConfigUI-title-inner"]')).toContainText('Clinical Data Model')
  await page.locator('[id="__item4-img"]').click()
  await page.getByRole('option', { name: 'Other Settings' }).click()
  await page.locator('[id="__item4-content"]').click()
  // Placeholder mapping
  await page.locator('[id="__item3-img"]').click()
  await page.locator('[id="__input8-__list23-0-inner"]').click()
  await page.locator('[id="__input8-__list23-0-inner"]').fill('$$SCHEMA$$."person"')
  await page.locator('[id="__input9-__list17-__list23-0-0-inner"]').click()
  await page.locator('[id="__input9-__list17-__list23-0-0-inner"]').fill('$$SCHEMA$$."person"')
  await page.locator('[id="__select1-__list23-0-arrow"]').click()
  await page.getByRole('option', { name: '"person_id"' }).click()
  await page.getByTitle('Add a Join Entity Table').click()
  await page.locator('[id="__input12-__list35-0-inner"]').click()
  await page.locator('[id="__input12-__list35-0-inner"]').fill('@COND')
  await page.locator('[id="__input13-__list35-0-inner"]').click()
  await page.locator('[id="__input13-__list35-0-inner"]').fill('$$SCHEMA$$."condition_occurrence"')
  await page.locator('[id="__select8-__list35-0-arrow"]').click()
  await page.getByRole('option', { name: '"person_id"' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[id="__select14-__list35-0-arrow"]').click()
  await page.getByRole('option', { name: '"condition_type_concept_id"' }).first().click()
  // Delete unused join entity
  await page.locator('[id="__button32-__list34-__list35-0-0"]').click()
  await page.getByTitle('Delete a Join Entity').click()
  await page.locator('[id="__button30-__list35-1"]').click()
  await page.locator('[id="__button28-__list22-__list23-0-0"]').click()
  // Terminology Services View Used for Catalog Attributes
  await page.locator('[id="__input16-__list39-0-inner"]').click()
  await page.locator('[id="__select18-__list39-0-label"]').click()
  await page.locator('[id="__select18-__list39-0-arrow"]').click()
  await page.locator('[id="__input16-__list39-0-inner"]').click()
  await page.locator('[id="__input16-__list39-0-inner"]').fill('$$VOCAB_SCHEMA$$."concept"')
  await page.locator('[id="__input16-__list39-0-inner"]').press('Enter')
  await page.waitForTimeout(1000)
  await page.locator('[id="__select18-__list39-0-arrow"]').click()
  await page.getByRole('option', { name: '"vocabulary_id"' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[id="__select19-__list39-0-arrow"]').click()
  await page.getByRole('option', { name: '"concept_code"' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[id="__select20-__list39-0-arrow"]').click()
  await page.getByRole('option', { name: '"concept_name"' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[id="__input17-__list43-0-inner"]').click()
  await page.locator('[id="__input17-__list43-0-inner"]').fill('$$VOCAB_SCHEMA$$."concept"')
  await page.waitForTimeout(1000)
  await page.locator('[id="__select21-__list43-0-arrow"]').click()
  await page.getByRole('option', { name: '"concept_id"' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[id="__select22-__list43-0-arrow"]').click()
  await page.getByRole('option', { name: '"concept_id"' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[id="__select23-__list43-0-arrow"]').click()
  await page.getByRole('option', { name: '"concept_name"' }).click()
  await page.locator('[id="__input18-__list44-0-inner"]').click()
  await page.locator('[id="__input18-__list44-0-inner"]').fill('$$VOCAB_SCHEMA$$."concept"')

  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'OK' }).click()

  // Data Model Setting
  await page.locator('[id="__xmlview1--configSectionPage--cdmMenu-img"]').click()
  await page.getByText('Basic Data').click()
  // Person Id
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Person Id')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('pid')
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').fill('CAST (@PATIENT."person_id" AS VARCHAR)')
  await page.locator('[id="__xmlview11--annotationsInput-inner"]').click()
  await page.locator('[id="__xmlview11--annotationsInput-inner"]').fill('person_id')

  // Patient Count
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Patient count')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('pcount')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.getByRole('radio', { name: 'Aggregate Attribute' }).click()
  await page.locator('[id="__xmlview11--AttributeAggregationFilter-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeAggregationFilter-inner"]')
    .fill('COUNT(DISTINCT(@PATIENT."person_id"))')
  await page.locator('[id="__xmlview11--AttributeType-label"]').click()
  await page.getByRole('option', { name: 'Number' }).click()
  // Gender
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Gender ')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('Gender_concept_name')
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeDataSource-inner"]')
    .fill("CASE WHEN @PATIENT.\"GENDER_CONCEPT_ID\" = 8532 THEN 'FEMALE' ELSE 'MALE' END")
  await page.getByRole('checkbox', { name: 'Off' }).click()
  await page.locator('[id="__xmlview11--AttributeReferenceExpression-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeReferenceExpression-inner"]').fill('@REF.CONCEPT_NAME')
  await page.locator('[id="__xmlview11--AttributeReferenceFilter-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeReferenceFilter-inner"]')
    .fill(
      "@REF.DOMAIN_ID = 'Gender' AND @REF.STANDARD_CONCEPT = 'S' AND JARO_SIMILARITY(lower(@REF.CONCEPT_NAME), lower('@SEARCH_QUERY')) >= 0.65"
    )

  // Age
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Age ')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('age')
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED' }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeDataSource-inner"]')
    .fill('YEAR(CURRENT_DATE) - @PATIENT."YEAR_OF_BIRTH"')
  await page.locator('[id="__xmlview11--AttributeType-label"]').click()
  await page.getByRole('option', { name: 'Number' }).click()
  // Defined Interactions
  await page.getByRole('link', { name: 'Defined Interactions (0)' }).click()
  await page.getByRole('button', { name: 'Add Interaction' }).click()
  await page.getByText('New Interaction - 1').click()
  await page.locator('[id="__xmlview5--interactionName-inner"]').click()
  await page.locator('[id="__xmlview5--interactionName-inner"]').fill('Condition Occurrence')
  await page.locator('[id="__xmlview5--interactionIDName-inner"]').click()
  await page.locator('[id="__xmlview5--interactionIDName-inner"]').fill('conditionoccurrence')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.locator('[id="__box6-inner"]').click()
  await page.locator('[id="__box6-inner"]').fill('@COND')
  // Person Id
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Person Id')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('pid')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED', exact: true }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').fill('CAST (@COND.person_id AS VARCHAR)')
  // Condition concept id
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Condition concept id')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('conditionconceptid')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED', exact: true }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').fill('@COND."CONDITION_CONCEPT_ID"')
  await page.locator('[id="__switch0"]').click()
  await page.locator('[id="__xmlview11--AttributeReferenceExpression-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeReferenceExpression-inner"]').fill('@REF.CONCEPT_ID')
  await page.locator('[id="__xmlview11--AttributeReferenceFilter-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeReferenceFilter-inner"]')
    .fill(
      "@REF.DOMAIN_ID = 'Condition' AND @REF.STANDARD_CONCEPT = 'S' AND JARO_SIMILARITY(CAST(@REF.CONCEPT_ID AS VARCHAR), '@SEARCH_QUERY') >= 0.85"
    )

  // Condition concept name
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute - 1').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Condition concept name')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('condition_occ_concept_name')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED', exact: true }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').fill('@TEXT.concept_name')
  await page.locator('[id="__switch0"]').click()
  await page.locator('[id="__xmlview11--AttributeReferenceExpression-inner"]').click()
  await page.locator('[id="__xmlview11--AttributeReferenceExpression-inner"]').fill('@REF.CONCEPT_NAME')
  await page.locator('[id="__xmlview11--AttributeReferenceFilter-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeReferenceFilter-inner"]')
    .fill(
      "@REF.DOMAIN_ID = 'Condition' AND @REF.STANDARD_CONCEPT = 'S' AND JARO_SIMILARITY(lower(@REF.CONCEPT_NAME), lower('@SEARCH_QUERY')) >= 0.65"
    )

  // Condition concept set
  await page.getByRole('button', { name: 'Add Attribute' }).click()
  await page.getByText('New Attribute -').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').click()
  await page.locator('[id="__xmlview11--attrName-inner"]').fill('Condition concept set')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').click()
  await page.locator('[id="__xmlview11--attrIDName-inner"]').fill('conditionconceptset')
  await page.locator('[id="__xmlview11--attrIDName-inner"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('radio', { name: 'ADVANCED', exact: true }).click()
  await page.locator('[id="__xmlview11--AttributeDataSource-inner"]').click()
  await page
    .locator('[id="__xmlview11--AttributeDataSource-inner"]')
    .fill('CAST (@COND."CONDITION_CONCEPT_ID" AS VARCHAR)')
  await page.locator('[id="__xmlview11--AttributeType-label"]').click()
  await page.getByRole('option', { name: 'Concept Set' }).click()

  // Validate the configuration
  await page.getByRole('button', { name: 'Validate' }).click()
  await expect(page.getByText('Success')).toBeVisible()
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: 'Preview' }).click()
  await expect(page).toHaveScreenshot({ maxDiffPixels: 100 })
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'Save & Activate' }).click()
  await page.getByRole('button', { name: 'OK' }).click()

  // PA configuration
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^Patient Analytics configConfigure patient analyticsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.waitForTimeout(2000)
  await page.locator('[id*="dataModelConfigurationsCombo-arrow"]').click()
  await page.getByRole('option', { name: 'TestConfig101' }).click()
  await page.getByRole('button', { name: 'Add Configuration' }).click()
  await page.getByRole('textbox', { name: 'Name : Enter Configuration' }).click()
  await page.getByRole('textbox', { name: 'Name : Enter Configuration' }).fill('CDM-Test101-PA')

  // filter cards
  await page.locator('[id="__filter2-icon"]').click()
  await page.waitForTimeout(1000)
  await page
    .locator('[class*="sapMCLI sapMLIB sapMLIB-CTX sapMLIBActionable sapMLIBFocusable"]')
    .filter({ hasText: 'Basic Data (4)' })
    .locator('[role="button"]')
    .click()

  await page.waitForTimeout(1000)
  await page
    .locator('tr')
    .filter({ hasText: 'Gender' })
    .locator('[headers*="__vbox"]')
    .locator('[role="checkbox"][aria-checked="false"]')
    .first()
    .click()
  await page
    .locator('tr')
    .filter({ hasText: 'Age' })
    .locator('[headers*="__vbox"]')
    .locator('[role="checkbox"][aria-checked="false"]')
    .first()
    .click()
  // charts
  await page.locator('[id="__filter3-icon"]').click()
  await page.getByText('Choose Attribute').first().click()
  await page.getByText('Basic Data', { exact: true }).click()
  await page.getByLabel('Age', { exact: true }).getByText('Age').click()
  await page.getByText('Choose Attribute').first().click()
  await page.getByText('Basic Data', { exact: true }).click()
  await page.getByLabel('Gender').getByText('Gender').click()
  await page.getByText('Choose Attribute').last().click()
  await page.getByText('Basic Data', { exact: true }).click()
  await page.getByLabel('Patient count').getByText('Patient count').click()
  // validate PA configuration
  await page.getByRole('button', { name: 'Validate' }).click()
  await expect(page.getByText('Configuration valid.')).toBeVisible()
  // save the PA configuration
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Configuration saved.')).toBeVisible()
  // Update the dataset
  await page.getByRole('link', { name: 'Datasets' }).click()
  await page.getByRole('row').filter({ hasText: 'Demo dataset' }).getByRole('button', { name: 'Select action' }).click()
  await page.getByRole('option', { name: 'Update dataset' }).click()
  await page.locator('#mui-component-select-paConfigOption').click()
  await page.getByRole('option', { name: 'CDM-Test101-PA' }).click()
  await page.waitForTimeout(1000)
  await page.getByRole('button', { name: 'Save' }).click()

  // Duplication of interaction
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^CDM configurationConfigure CDMConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByRole('button', { name: 'Back' }).click()
  await page.waitForTimeout(1000)
  await page
    .locator('[class*="sapMFlexBox sapMFlexBoxAlignContentStretch sapMFlexBoxAlignItemsStretch"]')
    .filter({ hasText: 'TestConfig101' })
    .getByText('TestConfig101')
    .click()
  await page.getByText('Active', { exact: true }).click()
  await page.getByRole('link', { name: 'Defined Interactions (1)' }).dblclick()
  await page
    .locator('[class*="sapMxConfFCItem"]:has-text("Condition Occurrence")')
    .getByRole('button', { name: 'Duplicate' })
    .click()
  await page.waitForTimeout(1000)
  await page.getByText('Condition Occurrence_copy').click()
  await page.locator('[title="Condition Occurrence_copy"] input').click()
  await page.locator('[title="Condition Occurrence_copy"] input').fill('Dups Condition Occurrence')
  await page.locator('[value*="Condition_Occurrence_copy"]').click()
  await page.locator('[value*="Condition_Occurrence_copy"]').fill('dups_conditionoccurrence')
  await page.locator('[value*="Condition_Occurrence_copy"]').press('Enter')
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.waitForTimeout(1000)
  await page.getByRole('button', { name: 'Save & Activate' }).click()
  await page.getByRole('button', { name: 'OK' }).click()

  // Back to PA configuration
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^Patient Analytics configConfigure patient analyticsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.locator('[id*="dataModelConfigurationsCombo-arrow"]').click()
  await page.waitForTimeout(1000)
  await page.getByRole('option', { name: 'TestConfig101' }).click()
  await page.waitForTimeout(1000)
  await page.getByText('CDM-Test101-PA', { exact: true }).click()
  await page.reload()
  await page.locator('[id="__filter0-icon"]').click()
  await page.locator('[id*="dataModelVersionCombo-arrow"]').click()
  await page.getByRole('option', { name: '- Active Version' }).click()
  await page.getByRole('button', { name: 'Keep Current Settings' }).click()
  await page.locator('[id="__filter2-icon"]').click()
  await page.waitForTimeout(1000)
  await page.locator('[role="toolbar"]:has-text("Dups Condition Occurrence")').locator('[id*="textoff"]').click()
  await page.getByRole('button', { name: 'Validate' }).click()
  await expect(page.getByText('Configuration valid.')).toBeVisible()
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Configuration saved.')).toBeVisible()

  // Cohort application
  await page.getByRole('link', { name: 'Account' }).click()
  await page.getByRole('button', { name: 'Switch to Researcher portal' }).click()
  await page.getByText('Demo dataset').first().click()
  await page.getByRole('link', { name: 'Cohorts' }).click()
  await page.waitForTimeout(1000)
  await page.getByRole('button', { name: 'D2E' }).click()
  await page.waitForTimeout(1000)
  await page.getByTitle('Add Filter Card').getByRole('button').click()
  await expect(page.getByRole('menuitem', { name: 'Dups Condition Occurrence' })).toBeVisible()

  // CDM configuration removide duplice definitions
  await page.getByRole('link', { name: 'Account' }).click()
  await page.getByRole('button', { name: 'Switch to Admin portal' }).click()
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^CDM configurationConfigure CDMConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByText('TestConfig101', { exact: true }).click()
  await page.getByText('Active', { exact: true }).click()
  await page.getByRole('link', { name: 'Defined Interactions (2)' }).click()
  await page
    .locator('[class*="sapMxConfFCItem"]:has-text("Dups Condition Occurrence")')
    .getByRole('button', { name: 'Delete' })
    .click()
  await page.getByLabel('Delete').getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'Save & Activate' }).click()
  await page.getByRole('button', { name: 'OK' }).click()

  // PA configuration update
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^Patient Analytics configConfigure patient analyticsConfigure$/ })
    .getByTestId('button')
    .click()
  await page.getByText('CDM-Test101-PA').click()
  await page.locator('[id="__filter0-icon"]').click()
  await page.reload()
  await page.locator('[id="__filter0-icon"]').click()
  await page.locator('[id*="dataModelVersionCombo-arrow"]').click()
  await page.getByRole('option', { name: '- Active Version' }).click()
  await page.getByRole('button', { name: 'Keep Current Settings' }).click()
  await page.getByRole('button', { name: 'Save' }).click()

  // CDM configure ducplication
  await page.getByRole('link', { name: 'Setup' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^CDM configurationConfigure CDMConfigure$/ })
    .getByTestId('button')
    .click()
  await page
    .locator('[class*="sapMFlexBox sapMFlexBoxAlignContentStretch sapMFlexBoxAlignItemsStretch"]')
    .filter({ hasText: 'TestConfig101' })
    .getByText('Duplicate')
    .click()
  await page.getByRole('textbox', { name: 'Title Enter name for' }).click()
  await page.getByRole('textbox', { name: 'Title Enter name for' }).fill('TestConfig102')
  await page.getByLabel('Duplicate Configuration').getByRole('button', { name: 'Duplicate' }).click()
  await page.getByRole('button', { name: 'Save & Activate' }).click()
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('link', { name: 'Defined Interactions (1)' }).click()
  await page.getByRole('button', { name: 'Duplicate' }).click()
  await page.getByText('Condition Occurrence_copy').first().click()

  await page.locator('[id*="--interactionName-inner"]').click()
  await page.locator('[id*="--interactionName-inner"]').fill('Condition Occurrence Autosaving Test')
  await page.getByRole('button', { name: 'Back' }).click()
  await page.waitForTimeout(1000)
  await page.locator('[class*="sapFfhCDMonfigLargeText"]').filter({ hasText: 'TestConfig102' }).click()
  await expect(page.getByText('Autosave')).toBeVisible()

  await page.getByText('TestConfig101', { exact: true }).click()
  const download2Promise = page.waitForEvent('download')
  await page.locator('[id="__button9-__xmlview1--configOverview--configVersionListing-3"]').click()
  const download2 = await download2Promise
  await page.getByRole('button', { name: 'Import Configuration' }).click()
  await page.getByRole('textbox', { name: 'Configuration Content to' }).click()
  await page
    .getByRole('textbox', { name: 'Configuration Content to' })
    .fill(
      '{"patient":{"conditions":{},"interactions":{},"attributes":{}},"censor":{},"advancedSettings":{"tableTypePlaceholderMap":{"factTable":{"placeholder":"@PATIENT","attributeTables":[]},"dimTables":[{"placeholder":"@COND","attributeTables":[],"hierarchy":true,"time":true,"oneToN":true,"condition":true}]},"tableMapping":{"@COND":"$$SCHEMA$$.\\"condition_occurrence\\"","@COND.PATIENT_ID":"\\"person_id\\""},"guardedTableMapping":{"@PATIENT":"$$SCHEMA$$.\\"person\\""},"language":["en","de","fr","es","pt","zh"],"others":{},"settings":{"fuzziness":0.7,"maxResultSize":5000,"sqlReturnOn":false,"errorDetailsReturnOn":false,"errorStackTraceReturnOn":false,"enableFreeText":true,"vbEnabled":true,"dateFormat":"YYYY-MM-dd","timeFormat":"HH:mm:ss","otsTableMap":{"@CODE":"$$VOCAB_SCHEMA$$.\\"concept\\""},"datasetId":"DEFAULT"},"shared":{},"schemaVersion":"3"}}'
    )
  await page.getByRole('textbox', { name: 'Title Enter name for' }).click()
  await page.getByRole('textbox', { name: 'Title Enter name for' }).fill('TestConfig103')
  await page.getByLabel('Import Configuration').getByRole('button', { name: 'Import' }).click()
  await page.getByRole('button', { name: 'Save & Activate' }).click()
  await expect(page.getByText('Success')).toBeVisible()
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: 'Back' }).click()

  await page
    .locator('[class*="sapMFlexBox sapMFlexBoxAlignContentStretch sapMFlexBoxAlignItemsStretch"]')
    .filter({ hasText: 'TestConfig101' })
    .getByText('Delete')
    .click()
  await page.getByLabel('Are you sure you want to').getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'OK' }).click()
  await page
    .locator('[class*="sapMFlexBox sapMFlexBoxAlignContentStretch sapMFlexBoxAlignItemsStretch"]')
    .filter({ hasText: 'TestConfig102' })
    .getByText('Delete')
    .click()
  await page.getByLabel('Are you sure you want to').getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'OK' }).click()
  await page
    .locator('[class*="sapMFlexBox sapMFlexBoxAlignContentStretch sapMFlexBoxAlignItemsStretch"]')
    .filter({ hasText: 'TestConfig103' })
    .getByText('Delete')
    .click()
  await page.getByLabel('Are you sure you want to').getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'OK' }).click()
})
