import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://localhost:443');
  await page.getByTestId('button').nth(1).click();
  await page.locator('input[name="identifier"]').click();
  await page.locator('input[name="identifier"]').fill('admin');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('Updatepassword12345');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByTestId('button').nth(1).click();
  await page.getByRole('button', { name: 'Switch to Admin portal' }).click();
  await page.getByRole('link', { name: 'Datasets' }).click();
  await page.getByRole('row', { name: 'Normal 1ae50de0-70b4-4b2a-' }).getByRole('button').nth(2).click();
  await page.getByRole('option', { name: 'Resources' }).click();
  await page.getByRole('button', { name: 'Add file' }).click();
  await page.getByRole('button', { name: 'Add file' }).setInputFiles('Cohorts_def.csv');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Add file' }).click();
  await page.getByRole('button', { name: 'Add file' }).setInputFiles('Cohorts_file.csv');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('row', { name: 'Normal 1ae50de0-70b4-4b2a-' }).getByRole('button').nth(2).click();
  await page.getByRole('option', { name: 'Resources' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download' }).nth(3).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Delete' }).nth(3).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
});
