#!/usr/bin/env bash
set -o nounset
set -o errexit
echo ${0##*/} ...
echo . INFO generate dotenv file with random secrets

# inputs
CADDY__ALP__PUBLIC_FQDN=${CADDY__ALP__PUBLIC_FQDN:-localhost}
DOCKER_TAG_NAME=${DOCKER_TAG_NAME:-develop}
DOCKER_TREX_TAG_NAME=${DOCKER_TREX_TAG_NAME:-develop}
ENV_TYPE=${ENV_TYPE:-local}
TLS__CADDY_DIRECTIVE=${TLS__CADDY_DIRECTIVE:-tls internal}
[ -v DOTENV_FILE ] || DOTENV_FILE=.env.${ENV_TYPE}
DOTENV_KEYS=$DOTENV_FILE.keys

echo . INPUTS TLS__CADDY_DIRECTIVE=\"$TLS__CADDY_DIRECTIVE\" DOTENV_FILE=$DOTENV_FILE

# vars
export GIT_BASE_DIR="$(git rev-parse --show-toplevel)"
[ $ENV_TYPE = local ] && [ -z DOCKER_TAG_NAME ] && DOCKER_TAG_NAME=local

source $GIT_BASE_DIR/scripts/lib.sh # functions here

echo ". INFO generate public & private keys - DB_CREDENTIALS__INTERNAL"
DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE=$(random-password 41)
DB_CREDENTIALS__INTERNAL__PRIVATE_KEY="$(DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE=$DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE openssl genpkey -algorithm RSA -aes-256-cbc -pkeyopt rsa_keygen_bits:4096 -pass env:DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE -quiet)"
DB_CREDENTIALS__INTERNAL__DECRYPT_PRIVATE_KEY="$(DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE=$DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE openssl rsa -in <(echo "${DB_CREDENTIALS__INTERNAL__PRIVATE_KEY}") -passin env:DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE)"
DB_CREDENTIALS__INTERNAL__PUBLIC_KEY="$(DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE=$DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE openssl rsa -in <(echo "${DB_CREDENTIALS__INTERNAL__PRIVATE_KEY}") -pubout -passin env:DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE)"

# action

cd $GIT_BASE_DIR
echo -n '' > $DOTENV_FILE

echo CADDY__ALP__PUBLIC_FQDN=$CADDY__ALP__PUBLIC_FQDN >> $DOTENV_FILE
echo DOCKER_TAG_NAME=$DOCKER_TAG_NAME >> $DOTENV_FILE
echo DOCKER_TREX_TAG_NAME=$DOCKER_TREX_TAG_NAME >> $DOTENV_FILE
echo ENV_TYPE=$ENV_TYPE >> $DOTENV_FILE
echo FHIR__CLIENT_ID=$(random-uuid) >> $DOTENV_FILE
echo FHIR__CLIENT_SECRET=$(random-password 64) >> $DOTENV_FILE
echo LOGTO__ALP_APP__CLIENT_ID=$(random-password 21) >> $DOTENV_FILE
echo LOGTO__ALP_APP__CLIENT_SECRET=$(random-password 30) >> $DOTENV_FILE
echo LOGTO__ALP_DATA__CLIENT_ID=$(random-password 21) >> $DOTENV_FILE
echo LOGTO__ALP_DATA__CLIENT_SECRET=$(random-password 30) >> $DOTENV_FILE
echo LOGTO__ALP_SVC__CLIENT_ID=$(random-password 21) >> $DOTENV_FILE
echo LOGTO__ALP_SVC__CLIENT_SECRET=$(random-password 30) >> $DOTENV_FILE
echo LOGTO_API_M2M_CLIENT_ID=$(random-password 21) >> $DOTENV_FILE
echo LOGTO_API_M2M_CLIENT_SECRET=$(random-password 30) >> $DOTENV_FILE; source $DOTENV_FILE
echo MINIO__SECRET_KEY=$(random-uuid) >> $DOTENV_FILE
echo PG_ADMIN_PASSWORD=$(random-password $DEFAULT_PASSWORD_LENGTH) >> $DOTENV_FILE
echo PG_SUPER_PASSWORD=$(random-password $DEFAULT_PASSWORD_LENGTH) >> $DOTENV_FILE
echo PG_WRITE_PASSWORD=$(random-password $DEFAULT_PASSWORD_LENGTH) >> $DOTENV_FILE
echo REDIS_PASSWORD=$(random-uuid) >> $DOTENV_FILE
echo DICOM__HEALTH_CHECK_PASSWORD=$(random-password $DEFAULT_PASSWORD_LENGTH) >> $DOTENV_FILE
echo STRATEGUS__KEYRING_PASSWORD=$(random-uuid) >> $DOTENV_FILE
echo TLS__CADDY_DIRECTIVE=\'"$TLS__CADDY_DIRECTIVE"\' >> $DOTENV_FILE

echo LOGTO__CLIENTID_PASSWORD__BASIC_AUTH=$(echo -n "${LOGTO_API_M2M_CLIENT_ID}:${LOGTO_API_M2M_CLIENT_SECRET}" | base64) >> $DOTENV_FILE
#echo PG__LOGTO_MANAGER_USER=postgres >> $DOTENV_FILE
echo PG__LOGTO_MANAGER_PASSWORD=$(random-password $DEFAULT_PASSWORD_LENGTH) >> $DOTENV_FILE

set-cpu-limit
set-memory-limit
gen-tls-internal

# echo DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE=\'"$DB_CREDENTIALS__INTERNAL__PRIVATE_KEY_PASSPHRASE"\' >> $DOTENV_FILE
# echo DB_CREDENTIALS__INTERNAL__PRIVATE_KEY=\'"$DB_CREDENTIALS__INTERNAL__PRIVATE_KEY"\' >> $DOTENV_FILE
echo DB_CREDENTIALS__INTERNAL__DECRYPT_PRIVATE_KEY=\'"$DB_CREDENTIALS__INTERNAL__DECRYPT_PRIVATE_KEY"\' >> $DOTENV_FILE
echo DB_CREDENTIALS__INTERNAL__PUBLIC_KEY=\'"$DB_CREDENTIALS__INTERNAL__PUBLIC_KEY"\' >> $DOTENV_FILE

# finalize
cat $DOTENV_FILE | grep = | awk -F= '{print $1}' | grep _ | sort -u > $DOTENV_KEYS
echo . INFO linecounts
wc -l $DOTENV_FILE $DOTENV_KEYS | sed '$d'
echo
