apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trex-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.global.storageClassName | default "default" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if not .Values.global.disableVolumeName }}
  volumeName: apptier-pv-1
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ .Values.global.storageClassName | default "default" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if not .Values.global.disableVolumeName }}
  volumeName: apptier-pv-3
  {{- end }}
