const _env = Deno.env.toObject();

export const env = {
  NODE_ENV: _env.NODE_ENV,
  GIT__USERNAME: _env.GIT__USERNAME,
  GIT__EMAIL: _env.GIT__EMAIL,
  GIT_DASHBOARDS_REPO_URL: _env.GIT_DASHBOARDS_REPO_URL,
  GIT_DASHBOARDS_REPO_BRANCH: _env.GIT_DASHBOARDS_REPO_BRANCH,
  GIT_RESULT_VIEWER_TEMPLATE_REPO_URL: _env.GIT_RESULT_VIEWER_TEMPLATE_REPO_URL,
  GIT_RESULT_VIEWER_TEMPLATE_REPO_BRANCH:
    _env.GIT_RESULT_VIEWER_TEMPLATE_REPO_BRANCH,
};

export const services = JSON.parse(_env.SERVICE_ROUTES || "{}");
