name: d2e/demosetup-dev

on:
  workflow_dispatch: # Allow manual triggering
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop

env:
  VERSION: develop


jobs:
  demosetup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        if: success() || failure()
        run: |
          npm install 

      - name: Initialise d2e
        if: success() || failure()
        id: init
        run: |
          npx d2e init 

      - name: Pull docker images
        if: success() || failure()
        id: pull
        run: |
          npx d2e -e -v develop pull
          docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}"

      - name: Start services
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: start
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            npx d2e -e -v ${{ env.VERSION }} start
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
      
      - name: Log status
        if: success() || failure()
        run: |
          echo DC_EXIT_CODE=$DC_EXIT_CODE | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_EXIT_CODE=${{ steps.start.outputs.exit_code }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_OUTCOME=${{ steps.start.outcome }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_TOTAL_ATTEMPTS=${{ steps.start.outputs.total_attempts }} | tee -a $GITHUB_STEP_SUMMARY
          DC_FAIL_COUNT=$(grep -icE "starting|unhealthy" $DOCKER_STATUS_FILE|| true)
          echo DC_FAIL_COUNT=$DC_FAIL_COUNT | tee -a $GITHUB_STEP_SUMMARY
      
      - name: Logs 
        if: success() || failure()
        run: |
          npx d2e -v ${{ env.VERSION }} logs

      - name: Patchdemodb
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: patchdemodb
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            npx d2e patchdemodb
            DC_EXIT_CODE=$?
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
            
      - name: Setupdemo
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: setupdemo
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            npx d2e -e -v ${{ env.VERSION }} setupdemo
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
  
      - name: Checkflow
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: checkflow
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            npx d2e checkflow
            DC_EXIT_CODE=$?
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      - name: Stop d2e services
        if: success() || failure()
        id: stop
        run: |
          npx d2e -e -v ${{ env.VERSION }} stop
      - name: Clean d2e services
        if: success() || failure()
        id: clean
        run: |
          echo "y" | npx d2e clean  
