name: HTTP Tests PG

permissions:
  contents: read

on:
  workflow_dispatch: # Allow manual triggering
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  merge_group:
  push:
    branches:
      - develop

env:
  VERSION: develop
  PLUGINS_SEED: '["d2e-flows", "d2e-ui", "d2e-atlas", "data-transformation-flow", "hades-flow", "trex-hana", "trex-pgwire", "d2e-fhir-server", "i2b2-flow", "data-management-flow"]'
  PGUSER: postgres
  PGPASSWORD: mypass
  PGHOST: localhost
  PGPORT: 5432
  PGDATABASE: postgres
  TESTSCHEMA: HTTP_${{github.run_id}}
  isTestEnv: "true"
  isHttpTestRun: "true"
  USE_TREX_DB_CONN: "true"

jobs:
  demosetup:
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Increase swapfile to 15G
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: npm install
        if: success() || failure()
        run: |
          npm install

      # - name: Patch seed config for e2e tests
      #   run: node ./scripts/patch-seed-for-e2e.js

      - name: Initialise d2e
        if: success() || failure()
        id: init
        run: |
          init_choice=y ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop init
      - uses: dorny/paths-filter@v3
        id: file_changes
        with:
          initial-fetch-depth: 1
          filters: |
            flow_base:
              - "flows/base/**"
            flow_i2b2:
              - "flows/i2b2/**"
            flow_data_management:
              - "flows/data_management/**"
            ui: 
              - "ui/**"

      - name: Build Flow base docker image
        if: steps.file_changes.outputs.flow_base == 'true'
        id: build_flow_base_image
        run: |
          docker build --build-arg GIT_COMMIT_ARG=${{ github.sha }} --build-arg BUILD_TYPE=OSS --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} --file ./flows/base/Dockerfile --platform linux/amd64 --attest type=provenance,disabled=true --tag ghcr.io/ohdsi/d2e/flow-base:develop ./flows
        
      - name: Build i2b2 docker image
        if: steps.file_changes.outputs.flow_i2b2 == 'true'
        id: build_i2b2_image
        run: |
          docker build --build-arg GIT_COMMIT_ARG=${{ github.sha }} --build-arg BUILD_TYPE=OSS --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} --file ./flows/i2b2/Dockerfile --platform linux/amd64 --attest type=provenance,disabled=true --tag ghcr.io/ohdsi/d2e/flow-i2b2:develop ./flows

      - name: Build data management docker image
        if: steps.file_changes.outputs.flow_data_management == 'true'
        id: build_dm_image
        run: |
          docker build --build-arg GIT_COMMIT_ARG=${{ github.sha }} --build-arg BUILD_TYPE=OSS --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} --file ./flows/data_management/Dockerfile --platform linux/amd64 --attest type=provenance,disabled=true --tag ghcr.io/ohdsi/d2e/flow-data-management:develop ./flows

      - name: Build docker images
        if: success() || failure()
        id: pull
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v develop -d ./functions build
          docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}"

      - name: Prune images
        if: always()
        id: prune
        run: |
          docker buildx prune -af

      - name: Start services
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: start
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 2
          retry_on: any
          command: |
            ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }}  -d ./functions start
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      - name: Log status
        if: success() || failure()
        run: |
          echo DC_EXIT_CODE=$DC_EXIT_CODE | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_EXIT_CODE=${{ steps.start.outputs.exit_code }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_OUTCOME=${{ steps.start.outcome }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_TOTAL_ATTEMPTS=${{ steps.start.outputs.total_attempts }} | tee -a $GITHUB_STEP_SUMMARY
          DC_FAIL_COUNT=$(grep -icE "starting|unhealthy" $DOCKER_STATUS_FILE|| true)
          echo DC_FAIL_COUNT=$DC_FAIL_COUNT | tee -a $GITHUB_STEP_SUMMARY

      - name: Logs
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions logs

      - name: Setupdemo
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: setupdemo
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 1
          retry_on: any
          command: |
            ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }}  -d ./functions setupdemo
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      - name: Logs
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions logs

      - name: Checkflow
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: checkflow
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 1
          retry_on: any
          command: |
            ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions checkflow
            DC_EXIT_CODE=$?
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      # - name: UI Setup bun
      #   if: ${{ steps.file_changes.outputs.ui == 'true' }}
      #   uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: 1.2.23
      # - name: UI Build
      #   if: ${{ steps.file_changes.outputs.ui == 'true' }}
      #   working-directory: ./ui
      #   env:
      #     CI: false
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y build-essential curl file git
      #     bun install
      #     bun build-all
      #     UI_BUILD_EXIT_CODE=$?
      #     [ $UI_BUILD_EXIT_CODE = 0 ] || { echo EXIT UI_BUILD_EXIT_CODE=$UI_BUILD_EXIT_CODE && exit $UI_BUILD_EXIT_CODE; }

      # - name: UI docker-compose-local
      #   if: ${{ steps.file_changes.outputs.ui == 'true' }}
      #   run: |
      #     sed -i 's|# - ./ui/resources:/usr/src/local-resources|- ./ui/resources:/usr/src/local-resources|' docker-compose-local.yml

      - name: Restart d2e services
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions stop
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions start

      - name: Wait for services to be ready to avoid mounting race condition
        if: ${{ steps.file_changes.outputs.ui == 'true' }}
        run: sleep 10

      ###########
      - name: Check status of docker containers
        run: |
          docker ps -a
          PGPASSWORD=$(echo $(docker exec d2e-trex printenv DEMO__DB_PASSWORD)
          echo "PGPORT: ${PGPORT}"
          echo "PGPASSWORD: ${PGPASSWORD}"
          echo "PGUSER: ${PGUSER}"
          echo "PGHOST: ${PGHOST}"
          echo "PGDATABASE: ${PGDATABASE}"
          echo "isHttpTestRun: ${isHttpTestRun}"
          echo "isTestEnv: ${isTestEnv:-false}"
          echo "TESTSCHEMA: ${TESTSCHEMA}"
          echo "USE_TREX_DB_CONN: ${USE_TREX_DB_CONN}"

      - name: Check PG DB connection
        run: |
          echo "PGPORT: ${PGPORT}"
          echo "PGPASSWORD: ${PGPASSWORD}"
          echo "PGUSER: ${PGUSER}"
          echo "PGHOST: ${PGHOST}"
          echo "PGDATABASE: ${PGDATABASE}"
          echo "isHttpTestRun: ${isHttpTestRun}"
          echo "isTestEnv: ${isTestEnv:-false}"
          echo "TESTSCHEMA: ${TESTSCHEMA}"
          echo "USE_TREX_DB_CONN: ${USE_TREX_DB_CONN}"
          sudo apt install -y postgresql-client
          pg_isready -d ${PGDATABASE} -h ${PGHOST} -p ${PGPORT} -U ${PGUSER}
          psql -h ${PGHOST} -p ${PGPORT} -U ${PGUSER} -d ${PGDATABASE}
      ###########
      # - name: UI Mounting build
      #   if: ${{ steps.file_changes.outputs.ui == 'true' }}
      #   run: |
      #     docker exec d2e-trex sh -c "rm -r /usr/src/data/plugins/\@data2evidence/d2e-ui/resources"
      #     docker exec d2e-trex sh -c "cp -r /usr/src/local-resources /usr/src/data/plugins/\@data2evidence/d2e-ui/resources"

      # - name: e2e tests setup
      #   run: |
      #     cd ./tests/e2e
      #     npm install
      #     npm run init

      # - name: e2e tests
      #   # continue-on-error: true
      #   run: |
      #     cd ./tests/e2e
      #     npm test

      # - name: Upload Error Context
      #   if: always() # Always run, even if the previous step fails
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: error-context
      #     path: tests/e2e/test-results/**/*

      - name: Logs
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions logs

      # - name: Publish Test Report
      #   if: always()
      #   uses: ctrf-io/github-test-reporter@v1
      #   with:
      #     report-path: "./tests/e2e/ctrf/*.json"
      #     file-report: true

      - name: Stop d2e services
        if: success() || failure()
        id: stop
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions stop

      - name: Prune system
        if: always()
        id: prune_system
        run: |
          docker system prune -af
