name: Docker Build - R Kernel and Enterprise Gateway 
run-name: ${{ github.event.inputs.GIT_BRANCH_NAME || github.head_ref || github.ref_name }}

on:
  push:
    branches:
      - SantanM/internal-1827_r-kernel
    workflow_dispatch:

concurrency:
  group: ${{ github.event.inputs.GIT_BRANCH_NAME || github.head_ref || github.ref_name }}-${{ github.event_name }}-docker-build-push-prune
  cancel-in-progress: true

env:
  GIT_BRANCH_NAME: ${{ github.event.inputs.GIT_BRANCH_NAME || github.head_ref || github.ref_name }} # workflow_dispatch || pull_request || push
  GIT_REPO_FULL_NAME: ${{ github.event.inputs.GIT_REPO_FULL_NAME || github.event.pull_request.head.repo.full_name || github.event.repository.full_name }} # workflow_dispatch || pull_request || push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        id: setup
        env:
          DOCKER_BUILD_PUSH_BOOL_OVERRIDE: true
        run: |
          DOCKER_BUILD_PUSH_BOOL_STR=true
          DOCKER_IMG_TAG_NAME=local
          echo DOCKER_BUILD_PUSH_BOOL_STR=$DOCKER_BUILD_PUSH_BOOL_STR | tee -a $GITHUB_OUTPUT | tee -a $GITHUB_STEP_SUMMARY
          echo DOCKER_IMG_TAG_NAME=$DOCKER_IMG_TAG_NAME | tee -a $GITHUB_OUTPUT | tee -a $GITHUB_STEP_SUMMARY
          echo GIT_BRANCH_NAME="${GIT_BRANCH_NAME}" | tee -a $GITHUB_OUTPUT | tee -a $GITHUB_STEP_SUMMARY
          echo GIT_REPO_FULL_NAME="${GIT_REPO_FULL_NAME}" | tee -a $GITHUB_OUTPUT | tee -a $GITHUB_STEP_SUMMARY

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo HOSTNAME=$HOSTNAME
          echo "$GITHUB_CONTEXT"
    outputs:
      DOCKER_BUILD_PUSH_BOOL_STR: ${{ steps.setup.outputs.DOCKER_BUILD_PUSH_BOOL_STR }}
      DOCKER_IMG_TAG_NAME: ${{ steps.setup.outputs.DOCKER_IMG_TAG_NAME }}
      GIT_BRANCH_NAME: ${{ steps.setup.outputs.GIT_BRANCH_NAME }}
      GIT_REPO_FULL_NAME: ${{ steps.setup.outputs.GIT_REPO_FULL_NAME }}

  bld:
    needs: setup
    env: 
      DOCKER_BUILD_ARG1: GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: d2e-enterprise-gateway
            directory: ./services/R-kernel
            context: ./services/R-kernel
            fileName: Dockerfile
          - name: d2e-r-ohdsi-kernel
            directory: ./services/R-kernel/kernels
            context: .
            fileName: Dockerfile
            build_arg1: ${{ env.DOCKER_BUILD_ARG1 }}

    uses: ./.github/workflows/services-docker-push-called.yml
    with:
      AZ_REG_REPOSITORY: ${{ matrix.name }}
      DOCKER_BUILD_CONTEXT_PATH: ${{ matrix.context }}
      DOCKER_BUILD_FILE_PATH: ${{ matrix.directory }}/${{ matrix.fileName }}
      DOCKER_BUILD_PUSH_BOOL_STR: ${{ needs.setup.outputs.DOCKER_BUILD_PUSH_BOOL_STR }}
      DOCKER_IMG_TAG_NAME: ${{ needs.setup.outputs.DOCKER_IMG_TAG_NAME }}
      GIT_BRANCH_NAME: ${{ needs.setup.outputs.GIT_BRANCH_NAME }}
      GIT_REPO_FULL_NAME: ${{ needs.setup.outputs.GIT_REPO_FULL_NAME }}
      DOCKER_BUILD_ARG1: ${{ matrix.build_arg1 || '' }}
    secrets: inherit
