name: d2e-functions/pa Run HTTP tests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
  workflow_dispatch:

# Run only one job per branch
concurrency:
  group: ${{ github.head_ref || github.ref_name }}-http-tests # Run the latest push
  cancel-in-progress: true # Cancel in progress jobs of the workflow of the branch

jobs:
  check_file_changes:
    runs-on: ubuntu-latest
    if: (github.ref_name == 'develop' ||  contains('release/', github.ref_name) || github.event_name == 'workflow_dispatch') || ( github.event_name == 'pull_request' && !github.event.pull_request.draft ) # Should run if branch is develop/release/workflow_dispatch and doesnt have a PR
    outputs:
      changes: ${{ steps.file_changes.outputs.src }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: file_changes
        with:
          initial-fetch-depth: 1
          filters: |
            src:
              - "functions/_shared/alp-libs/nodejs/**"
              - "functions/analytics-svc/**"
              - "functions/bookmark-svc/**"
              - "functions/cdw-svc/**"
              - "functions/mri-pa-config/**"
              - "functions/mri-pg-config/**"
              - "functions/query-gen-svc/**"
              - "services/mri-db/**"
              - "services/alp-logto/**"
              - "services/alp-pg-management/**"
              - ".github/workflows/functions-http-tests.yml"
              - "package.json"
              - "docker-compose.yml"

  run-http-tests:
    needs: [check_file_changes]
    if: (github.ref_name == 'develop' || contains('release', github.ref_name) || github.event_name == 'workflow_dispatch') || ( github.event_name == 'pull_request' && !github.event.pull_request.draft && needs.check_file_changes.outputs.changes == 'true' ) # Should run if branch is develop/release/workflow_dispatch and doesnt have a PR
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TESTSCHEMA: HTTP_${{github.run_id}}
      isTestEnv: "true"
      isHttpTestRun: "true"
      HANASERVER: ${{ secrets.HN_SG_FQDN }} # az-hn-db/SG_FQDN
      HDIPORT: ${{ vars.HN_SG_PORT }} # az-hn-db/DB Port
      HDIPW: ${{ secrets.HN_SG_ADMIN_PASSWORD }} # az-hn-db/Admin password
      HDIUSER: ${{ vars.HN_SG_ADMIN_USERNAME }} # az-hn-db/Admin user
      TESTPORT: ${{ vars.HN_SG_PORT }} # az-hn-db/DB Port
      TESTSYSTEMPW: ${{ secrets.HN_SG_ADMIN_PASSWORD }} # az-hn-db/Admin password

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Print OS details
        run: |
          uname -a
          lsb_release -a
          cat /etc/os-release

      - name: Add /usr/bin to PATH
        run: echo "export PATH=$PATH:/usr/bin" >> ~/.bashrc && source ~/.bashrc

      - name: Setup PostgreSQL
        run: |
          # install and start PG DB
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib -y
          sudo systemctl start postgresql
          sudo systemctl enable postgresql

      - name: Verify PostgreSQL connection
        env:
          PGHOST: localhost
          PGUSER: test_user
          PGDATABASE: test_db
          PGPASSWORD: Toor1234
        run: |
          psql -c "SELECT version();"
