name: d2e/services envConverter tests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop
      - "release/*"
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-env-converter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: check_file_changed
        with:
          filters: |
            env_converter_changed:
              - 'services/envConverter/**'
              - '.github/workflows/services-env-converter-test.yml'

      - name: Determine condition to run
        env:
          SHOULD_WF_RUN: ${{ env.BRANCH_NAME == 'develop' || contains('release/', env.BRANCH_NAME) || steps.check_file_changed.outputs.env_converter_changed == 'True' }}
        run: |
          echo WF_RUN=$SHOULD_WF_RUN | tee -a $GITHUB_ENV | tee -a $GITHUB_STEP_SUMMARY

      - name: Setup node if files have changed
        uses: actions/setup-node@v4
        if: env.WF_RUN == 'true'
        with:
          node-version: "18.20.4"

      # Run the step only with "env_converter_changed" equals "True"
      - name: Run unit tests if files have changed
        if: env.WF_RUN == 'true'
        run: |
          rm -rf package.json
          cd services/envConverter
          yarn install --prefer-offline
          yarn test
