name: d2e/stats repo notification

on:
  schedule:
    - cron: "0 22 * * 1" # UTC timing
  workflow_dispatch:
  
jobs:
  get-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo traffic stats
        id: traffic_stats
        run: |
          response=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_TRAFFIC_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/data2evidence/d2e/traffic/views\?per\=week) 
          
          echo "traffic_views=$(echo $response | jq -rc '.views' ) " >> $GITHUB_OUTPUT
          traffic_count=$(echo $response | jq -rc '.count' )
          traffic_uniques=$(echo $response | jq -rc '.uniques' )
          echo "traffic_output=Count:$traffic_count, Uniques:$traffic_uniques" >> $GITHUB_OUTPUT

      - name: json to markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: traffic_stats_table
        with:
          json: ${{ steps.traffic_stats.outputs.traffic_views }}
     
      - name: Discord notification traffic stats
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_STATISTICS }}
          username: ${{ github.actor }}
          content: "### d2e Repo Weekly Traffic Stats\n${{ steps.traffic_stats.outputs.traffic_output }}```\n${{ steps.traffic_stats_table.outputs.table }}```"

      - name: Get npm registry downloads stats
        id: npm_stats
        run: |
          response=$(curl -s https://api.npmjs.org/downloads/point/last-week/d2e) 
          echo "npm_downloads=$(echo $response | jq -rc . ) " >> $GITHUB_OUTPUT
          
      - name: json to markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: npm_stats_table
        with:
          json: "[${{ steps.npm_stats.outputs.npm_downloads }}]"
     
      - name: Discord notification traffic stats
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_STATISTICS }}
          username: ${{ github.actor }}
          content: "### NPM Package Weekly Download Stats\n```${{ steps.npm_stats_table.outputs.table }}```"

