name: d2e-ui/pa tests

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  pick_runner:
    runs-on: ubuntu-latest
    outputs:
      random_runner: ${{ steps.shuffle.outputs.random_runner }}
    steps:
      - id: shuffle
        run: echo "random_runner=$(shuf -e ubuntu-22.04 ubuntu-24.04 | head -n 1)" >> "$GITHUB_OUTPUT"
  test-mri-frontend:
    needs: [pick_runner]
    runs-on: ${{ needs.pick_runner.outputs.random_runner }}
    defaults:
      run:
        working-directory: ./ui
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v4

    - name: check if vue files has changed
      shell: bash
      # Give an id to the step, so we can reference it later
      id: check_vue_files_changed
      run: |
        # Fetch develop & get file changes from feature branch
        git fetch origin develop

        # Diff HEAD with the last commit of develop & filter for 'apps/vue-mri-ui-lib'
        diff=$(git diff --name-only origin/develop HEAD | grep '^apps/vue-mri-ui-lib' || :)

        # Check if a file under apps/vue-mri-ui-lib has changed (added, modified, deleted)
        hasDiff=$(if [ ${#diff} -gt 0 ] ; then echo "True" ; else echo "False"; fi)

        # Set the output named "vue_mri_ui_lib_changed"
        echo "vue_mri_ui_lib_changed=$hasDiff" >> $GITHUB_OUTPUT
        echo "Files changed: $diff"
        echo "vue-mri-ui-lib changed: $hasDiff"

    - name: Setup node if vue files have changed
      uses: actions/setup-node@v4
      if: github.ref_name == 'develop' || steps.check_vue_files_changed.outputs.vue_mri_ui_lib_changed == 'True'
      with:
        node-version: '18.14.0'

    - name: Setup pnpm if vue files have changed
      uses: pnpm/action-setup@v4
      if: github.ref_name == 'develop' || steps.check_vue_files_changed.outputs.vue_mri_ui_lib_changed == 'True'
      with:
        version: 10

    - name: Get pnpm store directory
      if: github.ref_name == 'develop' || steps.check_vue_files_changed.outputs.vue_mri_ui_lib_changed == 'True'
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      if: github.ref_name == 'develop' || steps.check_vue_files_changed.outputs.vue_mri_ui_lib_changed == 'True'
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Build Project
      if: github.ref_name == 'develop' || steps.check_vue_files_changed.outputs.vue_mri_ui_lib_changed == 'True'
      run: |
        pnpm install
        npx nx run vue-mri:test:ci
