name: 'Voting'
on:
  pull_request:
      types: [opened, synchronize, reopened, closed]

jobs:
  democracy:
    runs-on: ubuntu-latest
    environment: vote

    steps:
      - uses: actions/checkout@v4
      - name: Evaluate vote
        run: echo "approved"
